### PR TITLE
Feature/con 77

### PR DESCRIPTION
**Pull request by samuelraeburn**

### CODE REVIEW

**Comment by alexcamposruiz** [comment]
I looks like we need more testing for functions that now raise exceptions (set_number, take, ...). You only added one for write().

**Comment by alexcamposruiz** [comment]
I think we also need a new section in the docs about error management. It should simply explain that all internal DDS errors are raised as `rticonnextdds_connector.Error`. Other errors may be reported as `TypeError`, `AttributeError` (I don't know how consistent we are there).

You can add a new rst file and include it under Advanced topics.

**Comment by samuelraeburn** [comment]
I will add some unit tests, a lot of the APIs cannot actually fail
e.g., read and take I can't see from Connector a way to make them fail - any ideas?

**Comment by samuelraeburn** [comment]
Same question for getSamplesCount

**Comment by alexcamposruiz** [comment]
I'm merging this branch because I need these changes for CON-102. I can take care of some of the feedback. Let's create a new PR if we need more testing.

**Pull request merged**
