### PR TITLE
Feature/con 174 armv8

### PR DESCRIPTION
**Pull request by samuelraeburn**
- Handle armv8 archs and load the correct library

### CODE REVIEW

**Comment by samuelraeburn** [comment]
The changes made in PLATFORMS-1925 I do not think are correct anymore, but maybe I'm wrong, I wasn't involved with that. If they are, I'll need to update the release notes

**Comment by samuelraeburn** [comment]
Tested on bld-armv8:

```
[sam@bld-armv8 ~/connector-py-test-armv8/rticonnextdds-connector-py]$ python3 ./examples/python/simple/reader.py 
Traceback (most recent call last):
  File "./examples/python/simple/reader.py", line 18, in <module>
    import rticonnextdds_connector as rti
  File "/home/sam/connector-py-test-armv8/rticonnextdds-connector-py/examples/python/simple/../../../rticonnextdds_connector/__init__.py", line 9, in <module>
    from .rticonnextdds_connector import *
  File "/home/sam/connector-py-test-armv8/rticonnextdds-connector-py/examples/python/simple/../../../rticonnextdds_connector/rticonnextdds_connector.py", line 352, in <module>
    connector_binding = _ConnectorBinding() # pylint: disable=invalid-name
  File "/home/sam/connector-py-test-armv8/rticonnextdds-connector-py/examples/python/simple/../../../rticonnextdds_connector/rticonnextdds_connector.py", line 154, in __init__
    self.library = ctypes.CDLL(os.path.join(path, libname), ctypes.RTLD_GLOBAL)
  File "/usr/lib/python3.5/ctypes/__init__.py", line 347, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/sam/connector-py-test-armv8/rticonnextdds-connector-py/rticonnextdds_connector/../rticonnextdds-connector/lib/armv8Linux4gcc7.3.0/librtiddsconnector.so: cannot open shared object file: No such file or directory
[sam@bld-armv8 ~/connector-py-test-armv8/rticonnextdds-connector-py]$ mv ./rticonnextdds-connector/lib/armv8Linux4gcc7.3.0.temp/ ./rticonnextdds-connector/lib/armv8Linux4gcc7.3.0/
[sam@bld-armv8 ~/connector-py-test-armv8/rticonnextdds-connector-py]$ python3 ./examples/python/simple/reader.py 
Waiting for publications...
```

**Comment by samuelraeburn** [comment]
Still need to do the same work on JS connector. Can't do it until I get access to a armv8 machine with Node installed so i can add the correct logic

**Comment by adelleolson** [comment]
Sam, Why do you think the changes made in PLATFORMS-1925 no longer correct?



*From:* Sam [mailto:notifications@github.com]
*Sent:* Tuesday, January 12, 2021 7:15 AM
*To:* rticommunity/rticonnextdds-connector-py <
rticonnextdds-connector-py@noreply.github.com>
*Cc:* Subscribed <subscribed@noreply.github.com>
*Subject:* Re: [rticommunity/rticonnextdds-connector-py] Feature/con 174
armv8 (#57)



The changes made in PLATFORMS-1925 I do not think are correct anymore, but
maybe I'm wrong, I wasn't involved with that. If they are, I'll need to
update the release notes

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/rticommunity/rticonnextdds-connector-py/pull/57#issuecomment-758617293>,
or unsubscribe

**Comment by samuelraeburn** [comment]
Hey Adelle, the one I wasn't sure about is:
```
Wind River® Linux 8 (Arm v7) (Custom-supported platform)
```
I am going to check with Elaine

**Review by alexcamposruiz — APPROVED** [review]

**Comment by alexcamposruiz** [comment]
Make sure the arch string aarch64 will work in general

**Comment by alexcamposruiz** [comment]
Also, the JS and py PRs are inconsistent. In Js you still support loading the old arm, but not here.

**Review by alexcamposruiz — CHANGES_REQUESTED** [review]
See two comments

**Comment by samuelraeburn** [comment]
With regards to testing. I have still only tested on raspbuntu (which returns `aarch64` for the machine name). I do not think we have access to machines returning the other strings I am checking for.

**Review by alexcamposruiz — APPROVED** [review]

**Pull request merged**
